// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// updateColumnsInPlace
void updateColumnsInPlace(arma::mat& A, arma::uvec ind, const arma::mat& B);
RcppExport SEXP _cbce_updateColumnsInPlace(SEXP ASEXP, SEXP indSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    updateColumnsInPlace(A, ind, B);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_cbase();

static const R_CallMethodDef CallEntries[] = {
    {"_cbce_updateColumnsInPlace", (DL_FUNC) &_cbce_updateColumnsInPlace, 3},
    {"_rcpp_module_boot_cbase", (DL_FUNC) &_rcpp_module_boot_cbase, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_cbce(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
