// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// updateColumnsInPlace
void updateColumnsInPlace(NumericMatrix& A, const IntegerVector& ind, const NumericMatrix& B);
RcppExport SEXP _cbce_updateColumnsInPlace(SEXP ASEXP, SEXP indSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type B(BSEXP);
    updateColumnsInPlace(A, ind, B);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cbce_updateColumnsInPlace", (DL_FUNC) &_cbce_updateColumnsInPlace, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_cbce(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
