# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update the colmns ind of matrix A in place by matrix B
#' 
updateColumnsInPlace <- function(A, ind, B) {
    invisible(.Call(`_cbce_updateColumnsInPlace`, A, ind, B))
}

#'
#'@export
fast_bh_beta <- function(Tstat, alpha, shape1, shape2, lower = FALSE) {
    .Call(`_cbce_fast_bh_beta`, Tstat, alpha, shape1, shape2, lower)
}

#'
#'@export
fast_bh_chisq <- function(Tstat, alpha, df, lower = FALSE) {
    .Call(`_cbce_fast_bh_chisq`, Tstat, alpha, df, lower)
}

