# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Update the matrix A in place
#' 
#' @export
updateColumnsInPlace <- function(A, ind, B) {
    invisible(.Call(`_cbce_updateColumnsInPlace`, A, ind, B))
}

